import React from "react";
import {
  View,
  Text,
  TouchableOpacity,
  ScrollView,
  StyleSheet,
} from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { FontAwesome5 } from "@expo/vector-icons";
import { useStateContext } from "../../context/StateContext/StateContext";
import { COLORS, SIZES } from "../../constants/theme";

const TermsAndConditionScreen = ({ navigation }) => {
  const { colors } = useStateContext();

  const styles = StyleSheet.create({
    grandParent: {
      flex: 1,
      paddingHorizontal: SIZES.radius,
      paddingVertical: SIZES.radius,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: SIZES.padding,
    },
    heading: {
      fontSize: SIZES.h2,
      fontWeight: "bold",
      marginLeft: SIZES.base,
      color: colors.textColor,
    },
    back: {
      backgroundColor: COLORS.lightblue,
      padding: SIZES.base,
      borderRadius: 10,
      color: COLORS.darkBlue,
    },
    dashedLine: {
      marginTop: 10,
      borderWidth: 0.5,
      borderStyle: "dotted",
      borderColor: "grey",
      marginBottom: SIZES.padding,
    },
    policy: {
      marginBottom: SIZES.padding,
      color: colors.textColor,
      textAlign: "justify",
    },
    privacy: {
      marginBottom: SIZES.padding,
      color: colors.textColor,
      textAlign: "justify",
    },
  });

  return (
    <SafeAreaView style={styles.grandParent}>
      <ScrollView showsVerticalScrollIndicator={false}>
        <View style={styles.header}>
          <TouchableOpacity onPress={() => navigation.goBack()} style={styles.back}>
            <FontAwesome5 name="chevron-left" size={16} color={COLORS.darkBlue} />
          </TouchableOpacity>

          <View>
            <Text style={styles.heading}> Terms and Condition</Text>
          </View>
        </View>
        <View style={styles.dashedLine} />
        <Text style={styles.policy}>
          This Privacy Policy describes Our policies and procedures on the
          collection, use and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law
          protects You.
        </Text>
        <Text style={styles.policy}>
          We use Your Personal data to provide and improve the Service. By using
          the Service, You agree to the collection and use of information in
          accordance with this Privacy Policy.
        </Text>
        <Text style={styles.policy}>
          This Privacy Policy was generated by TermsFeed App Privacy Policy
          Generator. The words of which the initial letter is capitalized have
          meanings defined under the following conditions. The following
          definitions shall have the same meaning regardless of whether they
          appear in singular or in plural.
        </Text>
        <Text style={styles.policy}>
          The Company will retain Your Personal Data only for as long as is
          necessary for the purposes set out in this Privacy Policy. We will
          retain and use Your Personal Data to the extent necessary to comply
          with our legal obligations (for example, if we are required to retain
          your data to comply with applicable laws), resolve disputes, and
          enforce our legal agreements and policies.
        </Text>
        {/* ... (Continue adding your text) */}
        <View style={styles.dashedLine} />
        <Text style={styles.privacy}>
          Usage Data may include information such as Your Device's Internet
          Protocol address (e.g. IP address), browser type, browser version,
          the pages of our Service that You visit, the time and date of Your
          visit, the time spent on those pages, unique device identifiers, and
          other diagnostic data.
        </Text>
        <Text style={styles.privacy}>
          When You access the Service by or through a mobile device, We may
          collect certain information automatically, including, but not limited
          to, the type of mobile device You use, Your mobile device unique ID,
          the IP address of Your mobile device, Your mobile operating system,
          the type of mobile Internet browser You use, unique device identifiers
          and other diagnostic data.
        </Text>
        <Text style={styles.privacy}>
          We may also collect information that Your browser sends whenever You
          visit our Service or when You access the Service by or through a
          mobile device.
        </Text>
      </ScrollView>
    </SafeAreaView>
  );
};

export default TermsAndConditionScreen;
